### ISSUE TITLE
Horizontal scroll when hamburger menu is open on mobile

### ISSUE THREAD

**Issue by Fontler** [Evavic44/responsive-navbar-with-dropdown#4]
Hello and thank you Victor for a great tutorial! There seems to be an issue with horizontal scroll when the hamburger menu is open on mobile, especially if you open the Browse dropdown. See the attached screenshot bellow.

![image](https://github.com/Evavic44/responsive-navbar-with-dropdown/assets/94294697/c07c8f6d-d0d4-485c-9fd6-6aa011521abf)

**Comment by Evavic44** [comment]
Thanks for spotting this issue, @Fontler.
The issue seems to be coming from the explicit width of `480px` set on the `.menu-bar li:first-child .dropdown` class.

```css
.menu-bar li:first-child .dropdown {
  flex-direction: initial;
  min-width: 480px;
}
```

To fix this, simply set the `min-width` to 100% inside the `@media (max-width: 1100px)`. 
Like so:

```css
.menu-bar li:first-child .dropdown {
  min-width: 100%;
}
```

I've updated this repo with the desired changes including the codepen file. Do take a look if you want to. 👍
